### ISSUE TITLE
MIDI scale skips steps

### ISSUE THREAD

**Issue by thijz** [x42/midifilter.lv2#21]
hi,

I'm using your 'MIDI scale CC value' LV2 plugin in Carla
as input it gets CC values that range from 0 to 16 and i want to scale these values up to 0-127
i have set the scaling factor to 8 to accomplish this

the strange thing is that the conversion works as expected except for input values 9 and 13 :
9 gets mapped to 64 (should be 72)
13 gets mapped to 96 (should be 104)
(verified the above using GMIDImonitor)

i have tried playing with all the parameters, but for some reason 9 is treated as 8 and 13 is treated as 12

am i missing something ?

i tried to see what version of the plugin i'm using but cant quite figure out where i can see this

**Comment by x42** [comment]
Since it's off by 8 this would rather indicate that the input is already off by one!

The factor for multiplication is floating-point and rounding happens after multiplication;  line 72:
https://github.com/x42/midifilter.lv2/blob/6aa5893601516e5342a0caf3eeb3eae5e59365f7/filters/scalecc.c#L64-L72

I cannot reproduce this in jalv nor Ardour:

![midi-cc-scale](https://user-images.githubusercontent.com/30246/61004629-ac0c7500-a366-11e9-8776-1298b7485335.png)

Can you double-check that the input is really 9 on a value range from 0..127?

**Comment by thijz** [comment]
Thanks for the quick reply !

On my test setup i had 2 midimonitors running simultaneously on both the in- and output of the CC scale plugin.
The input monitor shows all 0-16 steps consistently.

Some more info (not sure if relevant) : i'm using CH16 on the input, midi comes from a BCR2000 where i have configured 2 knobs to output a value between 0 and 16.  When using any of these knobs as input for the plugin i can see the expected 0-16 values, but on the output always skips the scaled 9 and 13 inputs.

I will add a screenshot of the midi monitors asap

**Comment by thijz** [comment]
![image](https://user-images.githubusercontent.com/1384210/61032334-882a4d00-a3c1-11e9-8bb3-4aa93061e7fd.png)
settings :
![image](https://user-images.githubusercontent.com/1384210/61032274-6761f780-a3c1-11e9-8dd4-8ad888441538.png)

![image](https://user-images.githubusercontent.com/1384210/61032369-99735980-a3c1-11e9-9672-905d3c8a8139.png)

**Comment by thijz** [comment]
forgot to mention : 
i also simplified the above setup so only the scaling plugin is connected to the BCR but the results are the same

**Comment by x42** [comment]
So far I have no explanation how this can happen.

Could you try to run the plugin standalone? just jack to rule out any issues introduced by other applications.

Only jackd & a2jmidid. Something like:

```
jalv.gtk http://gareus.org/oss/lv2/midifilter#scalecc &
gmidimonitor  &
jack_connect "MIDI Scale CC Value:midiout" "MIDI monitor:midi_in"
jack_connect "BCR 2000 [44] (capture): BCR2000 MIDI 1" "MIDI Scale CC Value:midiin"
```

If that still produces the issue: Are you comfortable with compiling the plugins from source to test?

```
# install c compiler + lv2 SDK
sudo apt-get install build-essential lv2-dev curl patch

# compile plugin                                                                                                                                                                               
cd /tmp
git clone git://github.com/x42/midifilter.lv2.git
cd midifilter.lv2/
# add debug print
curl http://paste.debian.net/plain/1091260 | patch -p1
#compile it
make

# install to $HOME/.lv2
 mkdir -p ~/.lv2
 ln -s -T `pwd`/build ~/.lv2/midifilter.lv2

# you don't have to un-install the system-wide version, `jalv` will automatically pick the latest version
# just run the test now. launch the plugin in jalv from a terminal and the plugin will print
# values it receives  and sends  example:
## ScaleCC chn:01 param:001 value (001 * 8.000000 + 0.000000) = 008
## ScaleCC TX: b0 01 08


# uninstall later:
 rm ~/.lv2/midifilter.lv2
```

**Comment by thijz** [comment]
did the test with jalv and that works as expected !
guess i'll have to dig in to Carla a bit deeper ...

thank you so much for your quick help and even more for the great plugins !!!

screenshot of both in and output of the scaling plugin connected to the same midi monitor : 
![image](https://user-images.githubusercontent.com/1384210/61076086-b89ed500-a41b-11e9-85bf-2502ce3ccd8f.png)
