### ISSUE TITLE
MIDI Key-Range Filter's lowest note does't go higher than C-1

### ISSUE THREAD

**Issue by unfa** [x42/midifilter.lv2#25]
I am unable to make the Lowest Note higher than C-1.

I would expect both fileds to cover the whole range of MIDI notes.

![image](https://user-images.githubusercontent.com/491704/82034671-cad24b00-969e-11ea-86c3-a4718fb15f1a.png)

**Comment by x42** [comment]
C-1 is the lowest MIDI note(0), and G9 the highest (127).

**Comment by x42** [comment]
Octave -1 : 0..11
Octave  0: 12..23
...
Octave 9: 120..127 (ends a G9)

**Comment by unfa** [comment]
I am not sure we're on the same page. I thought with this plug-in I can for example only send notes between C4 and C5, ignoring all the rest.

And for that I need to set the Lowe note  to C4, and the Higher note to C5, but I the Lower note is stuck at C-1. I think it's a bug.

**Comment by x42** [comment]
> I thought with this plug-in I can for example only send notes between C4 and C5, ignoring all the rest.

That is correct.

>And for that I need to set the Lowe note to C4, and the Higher note to C5, but I the Lower note is stuck at C-1. I think it's a bug.

It's not a bug in the plugin. It's a bug in the host that you're using.

**Comment by unfa** [comment]
Oh, so I should report this problem for Ardour?
I'd never think of that.

Maybe I'll try to reproduce this in Ardour 6...

**Comment by x42** [comment]
> I'm using this plug-in in Ardour 5.12, if that's any help.

Indeed it does. the bug was fixed in Ardour 6.0-pre0-57-gd931f4f69d (Sept 2017). I forgot that A5 had this issue. IIRC Carla (and jalv?) were fixed around the same time.
The underlying issue was:  128 possible values, but only 127 steps between.

**Comment by unfa** [comment]
Hmm, I see. Thanks for the explanation.
I've had some major problems with Ardour 6 a few months back, so maybe they are fixed now so I could use it instead.
