### ISSUE TITLE
Note to PC

### ISSUE THREAD

**Issue by Samantha-uk** [x42/midifilter.lv2#35]
I'm running a MOD Dwarf and tho I can see Note to PC is one of the filters in this codebase, I cannot for the life of me see it as a plugin on the Dwarf.

Is there some technical reason it is not included?

**Comment by x42** [comment]
MOD forked the plugin set, and maintains a separate version at
https://github.com/moddevices/mod-lv2-data/tree/master/plugins-fixed/midifilter.lv2
You will have to contact them

**Comment by Samantha-uk** [comment]
Thank you, I'll do that.
