### ISSUE TITLE
Tonal Pedal does not work

### ISSUE THREAD

**Issue by dcoredump** [x42/midifilter.lv2#39]
Hi!

thanks for your famous miditools! I need the TonePedal for the NoizeMaker because it does not support the sustain pedal. Unfortunately, it doesn't work: nothing happens. I tried on MOD-Duo and on Zynthian.

Can you take a look at this?

TIA, Holger

**Comment by dcoredump** [comment]
In addition to my last message: Sostenuto works on both platforms as expected for CC 64.

**Comment by x42** [comment]
I've just tested in Ardour. Works as documented. The upper MIDI region is the input, and green line shows CC 64.. and the resulting MIDI is at the bottom:
![image](https://github.com/x42/midifilter.lv2/assets/30246/eda77e44-59cd-4399-93c1-99f88ae73506)

**Comment by dcoredump** [comment]
Thanks @x42 for testing and showing!

I have now also got the TonePedal running in the Zynthian MOD UI. It still doesn't work with MOD-Duo.
But you're right: the plugin itself works.
