### ISSUE TITLE
Midi controlled slider skips zero and passes from -1 to +1

### ISSUE THREAD

**Issue by MichelV87** [x42/midifilter.lv2#9]
In "Midi Chromatic Transpose" plugin in Carla host, slider for semi-tones values cannot be set to 0 from a midi controller. A value of 63 sets the slider to -1 and a value of 64 sets it to +1. Impossible to get 0.
 `midifilter.ttl` file :
`ControlPort ; lv2:index 4 ; lv2:symbol "transpose" ; lv2:name "Transpose"; lv2:minimum -72 ; lv2:maximum 72 ; lv2:default 0; lv2:portProperty lv2:integer ]`
It seems that these 145 values leads to a rounding when mapping them from the 128 of a controller so the 0 value is skipped.
I first open an issue in Carla Github : see https://github.com/falkTX/Carla/issues/327#issuecomment-165536739

**Comment by x42** [comment]
mmh that's an interesting issue.  so -63..+64   (range: 127) would resolve this.
worst-case a user would have to chain two of those if transposing > 64 semitones is needed.

Alternatively a range:  -127..+127  should allow to get to 0 but only steps of two :(
let's see what falktx thinks.

**Comment by MichelV87** [comment]
It's OK now with a range of -64..+63.
Issue fixed !

**Comment by x42** [comment]
wait, fixed how?

**Comment by x42** [comment]
https://github.com/x42/midifilter.lv2/blob/master/filters/miditranspose.c#L10 still reads -72, 72.
I'm tempted to change it, unless a better solution comes up.

**Comment by MichelV87** [comment]
Fixed on my machine by editing midifilter.ttl. Not for other users !
